### ISSUE TITLE
Spike how to get content from all repositories

### ISSUE THREAD

**Issue by PWKad** [aurelia/app-documentation#2]
The docs app should be able to load content from each repository without being rate limited by github.  @jdanyow mentioned trying out rawgit to accomplish this so I'll check this out and see if we can use it or something similar to prevent being rate limited.

Each repo should have an index file of some sort in addition to the api.json which has a list of content that is available for that repository to allow the docs to eager load a list and then load the corresponding files on demand.

Feedback welcome, I'll post results of the spike in this issue.

**Comment by jdanyow** [comment]
:+1: 

Wondering if there's a way we can get a repository's list of tags/releases without being rate-limited or if we need to list the tags in the index file you mentioned.

https://rawgit.com/faq#cdn-ttl

**Comment by PWKad** [comment]
I think the rawgit spike is complete.  We have a good idea for how to do this thanks to @jdanyow 's recommendation to use rawgit.  Looks to be working out well.  Closing this one.
